import axios from 'axios';

type ApplicationEmailPayload = {
  to?: string | null;
  applicantName: string;
  jobTitle: string;
  company: string;
  applicationUrl: string;
};

export class EmailService {
  private readonly apiKey = process.env.RESEND_API_KEY;
  private readonly from = process.env.RESEND_FROM_EMAIL || 'SwipeConnect <onboarding@resend.dev>';

  public get isConfigured() {
    return Boolean(this.apiKey);
  }

  async sendApplicationConfirmation(payload: ApplicationEmailPayload): Promise<{ sent: boolean; id?: string; reason?: string }> {
    if (!this.apiKey) {
      return { sent: false, reason: 'RESEND_API_KEY is not configured.' };
    }

    if (!payload.to) {
      return { sent: false, reason: 'Applicant email is missing.' };
    }

    const subject = `Application queued: ${payload.jobTitle} at ${payload.company}`;
    const text = [
      `Hi ${payload.applicantName},`,
      '',
      `SwipeConnect queued your application for ${payload.jobTitle} at ${payload.company}.`,
      `Next step/application link: ${payload.applicationUrl}`,
      '',
      'This confirmation was generated by SwipeConnect.',
    ].join('\n');

    const html = `
      <div style="font-family:Inter,Arial,sans-serif;line-height:1.5;color:#111827">
        <h2 style="margin:0 0 12px">Application queued</h2>
        <p>Hi ${payload.applicantName},</p>
        <p>SwipeConnect queued your application for <strong>${payload.jobTitle}</strong> at <strong>${payload.company}</strong>.</p>
        <p><a href="${payload.applicationUrl}" style="color:#db2777">View application link</a></p>
        <p style="color:#6b7280;font-size:13px">This confirmation was generated by SwipeConnect.</p>
      </div>
    `;

    try {
      const response = await axios.post(
        'https://api.resend.com/emails',
        {
          from: this.from,
          to: payload.to,
          subject,
          text,
          html,
        },
        {
          headers: {
            Authorization: `Bearer ${this.apiKey}`,
            'Content-Type': 'application/json',
          },
          timeout: 10000,
        }
      );

      return { sent: true, id: response.data?.id };
    } catch (error: any) {
      console.error('Resend email error:', error.response?.data || error.message);
      return {
        sent: false,
        reason: error.response?.data?.message || error.message || 'Resend request failed.',
      };
    }
  }
}
